### PR TITLE
links, date vs datetime, formatted numbers

### PR DESCRIPTION
**Pull request by FraBle**
I introduced the support for links inside cells (with a new event: link-clicked).
Furthermore I added some small changes regarding date vs. datetime and the formatting of numbers.

### CODE REVIEW

**Comment by David-Mulder** [comment]
@Frable: Okay, having gone through your pull request I see some valid fixes, but I think your implementation of links is overly specific without good reason. The same effect could be quite simply achieved by extending the `row-tap` event to include the column or adding a `cell-tap` event (as I now did) and then doing 

```
<paper-datatable-column type="object" on-cell-tap="{{myFunction}}" [...]>
    <a href="[[value.href]]">[[value.text]]</a>
</paper-datatable-column>
```

Either way, as far as fixes/other extensions go:
- I considered adding `datetime` as well, but I decided against this as it breaks with the JS type system. This can however be quite simply achieved by setting the `format-value` property and overwriting it with a custom function. I have now added an example of this in `demo/paper-datatable.html`.
- What is the idea of the `toLocaleString` on a number without providing a locale? As far as I know this will format a `Number` according to the system locale which is often undesired behaviour (living in a non-English speaking country I know first hand how irritating it is when components default to the OS locale rather than their own site), but there might be something I am missing?
- Complex objects shouldn't default to `toString` if the `type` is not `String` and returning just `return value` will cause it to trigger `toString`, so that would be clearly incorrect. That's why I showed a `?` as the representation of complex objects is simply unknown, however as you edited this I guess this isn't entirely clear, so I added a `console.warn`.

By the way, I might sound super critical now, but I do think that your comments _definitely_ allowed me to improve the component and if you think something isn't possible with the above changes do let me know.

**Comment by FraBle** [comment]
@David-Mulder:
- `cell click events`: true, I like your implementation way more. The one I proposed was the easiest one to go for me, since I needed it for a project as fast as possible. Your way is more polymer-like, that's what I like!
- `datetime`: yes, I was concerned about the JS type system as well. I guess `format-value` is the way to go and I will look into your example.
- `toLocaleString`: for my purpose the system locale was fine since I'm in the U.S. right now. But true, I didn't consider the user's location.
- `type`: makes sense, no further questions.

I basically adapted your library to the needs I have with my current project. Your feedback gives me a lot of insights on what I have to learn and look further into.

Btw: Why is the cell type parameter in uppercase ("String") since you always have to use the conversion `.toLowerCase()`?

ps: I really like your component and the work you put into it!

**Comment by David-Mulder** [comment]
@FraBle So everything you wanted to do is working now? And if you try updating: I am sorry that I made a couple of backwards incompatible changes. You might not even encounter them, but yeah, that's why I am still in the `0.x.y` version range.

And regarding your question at the end: I write them with an uppercase in the examples because that's the name of the type objects, but I also know that a lot of users will prefer writing them in lowercase, so by doing the `.toLowerCase()` I am able to do a case insensitive compare which is just the best way to do these things.

**Comment by FraBle** [comment]
@David-Mulder: Yes, everything is working for me. And yes, it makes sense to support both ways of writing the cell type!

**Pull request closed without merging**
